name: Request Subdomain
description: Request a free visitme.qzz.io subdomain
title: "[SUBDOMAIN]: "
labels:
  - subdomain

body:
  - type: input
    id: subdomain
    attributes:
      label: Subdomain
      description: Desired subdomain
      placeholder: alex
    validations:
      required: true

  - type: input
    id: target
    attributes:
      label: GitHub Pages URL
      description: Target website
      placeholder: alex.github.io
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Tell us about your project
      placeholder: Portfolio, blog, game...
